import JSZip from 'jszip';
import { getDb, STORES } from './db';
import { ArchiveBackupManifest, ChatArchiveMetadata, StoredAttachment } from '../../types/storage';
import { Message, ParsedChat } from '../../types/chat';
import { getArchiveMetadata, deleteArchive } from './archive-repository';
import { getArchiveAttachments, saveArchiveAttachments } from './attachment-repository';
import { ImportedMediaFile } from '../../types';

export interface RestoreOptions {
  mode?: 'error-if-exists' | 'copy' | 'replace';
  onProgress?: (status: string) => void;
}

export interface RestoreResult {
  restoredArchive: ChatArchiveMetadata;
  wasCollision: boolean;
  actionTaken: 'created' | 'copied' | 'replaced';
}

/**
 * Creates and downloads a portable backup ZIP for a given archive ID.
 * Complies with Requirements 28-34:
 * Manifest, messages.json, and attachments/ folder.
 */
export async function createArchiveBackupZip(
  archiveId: string,
  onProgress?: (status: string) => void
): Promise<Blob> {
  const metadata = await getArchiveMetadata(archiveId);
  if (!metadata) {
    throw new Error(`Archive not found: ${archiveId}`);
  }

  onProgress?.('Preparing archive data...');
  const db = await getDb();

  // Load messages
  const messages: Message[] = await new Promise((resolve, reject) => {
    const transaction = db.transaction([STORES.MESSAGES], 'readonly');
    const store = transaction.objectStore(STORES.MESSAGES);
    const index = store.index('chatId');
    const request = index.getAll(archiveId);

    request.onsuccess = () => resolve(request.result || []);
    request.onerror = () => reject(request.error || new Error('Failed to load messages for backup'));
  });

  // Load attachments
  onProgress?.('Reading stored media...');
  const attachments: StoredAttachment[] = await getArchiveAttachments(archiveId);

  // Build ZIP
  onProgress?.('Packaging backup archive...');
  const zip = new JSZip();

  const manifest: ArchiveBackupManifest = {
    format: 'whatsapp-chat-archive',
    version: 1,
    createdAt: new Date().toISOString(),
    archive: metadata,
    attachmentFileNames: attachments.map((a) => a.fileName),
  };

  zip.file('manifest.json', JSON.stringify(manifest, null, 2));
  zip.file('messages.json', JSON.stringify(messages, null, 2));

  if (attachments.length > 0) {
    const attachmentsFolder = zip.folder('attachments');
    if (attachmentsFolder) {
      for (const att of attachments) {
        let content: any = att.data;
        if (!content && att.blob) {
          if (typeof att.blob.arrayBuffer === 'function') {
            content = await att.blob.arrayBuffer();
          }
        }
        if (content) {
          attachmentsFolder.file(att.fileName, content);
        }
      }
    }
  }

  onProgress?.('Compressing backup...');
  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
}

/**
 * Downloads a Blob as a file in the browser.
 */
export function downloadBackupBlob(blob: Blob, archiveTitle: string): void {
  const sanitizedTitle = archiveTitle.replace(/[^a-zA-Z0-9_\-]/g, '_').slice(0, 40);
  const fileName = `${sanitizedTitle}-backup.zip`;

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Validates and restores a portable backup ZIP into IndexedDB.
 * Complies with Requirements 29-32:
 * Robust validation, version checking, and duplicate handling.
 */
export async function restoreArchiveFromBackup(
  backupFile: File | Blob,
  options: RestoreOptions = {}
): Promise<RestoreResult> {
  const { mode = 'error-if-exists', onProgress } = options;

  onProgress?.('Reading backup file...');
  const zip = new JSZip();

  let loadedZip: JSZip;
  try {
    loadedZip = await zip.loadAsync(backupFile);
  } catch {
    throw new Error('Invalid backup file. The uploaded file is not a valid ZIP archive.');
  }

  // 1. Validate manifest.json
  const manifestFile = loadedZip.file('manifest.json');
  if (!manifestFile) {
    throw new Error('Invalid backup: Missing manifest.json in the archive.');
  }

  let manifest: ArchiveBackupManifest;
  try {
    const manifestStr = await manifestFile.async('string');
    manifest = JSON.parse(manifestStr);
  } catch {
    throw new Error('Invalid backup: manifest.json is malformed or corrupted.');
  }

  if (manifest.format !== 'whatsapp-chat-archive') {
    throw new Error('Unsupported backup format. This file was not generated by WhatsApp ChatBook.');
  }

  if (manifest.version !== 1) {
    throw new Error(`Unsupported backup version (${manifest.version}). This version cannot be restored.`);
  }

  if (!manifest.archive || !manifest.archive.id || !manifest.archive.title) {
    throw new Error('Invalid backup: manifest.json does not contain valid archive metadata.');
  }

  // 2. Validate messages.json
  const messagesFile = loadedZip.file('messages.json');
  if (!messagesFile) {
    throw new Error('Invalid backup: Missing messages.json in the archive.');
  }

  let messages: Message[];
  try {
    const messagesStr = await messagesFile.async('string');
    messages = JSON.parse(messagesStr);
    if (!Array.isArray(messages)) {
      throw new Error('messages.json is not an array.');
    }
  } catch {
    throw new Error('Invalid backup: messages.json is malformed or corrupted.');
  }

  // 3. Check for existing archive collision
  const existingArchive = await getArchiveMetadata(manifest.archive.id);
  const wasCollision = !!existingArchive;

  let targetArchiveId = manifest.archive.id;
  let targetTitle = manifest.archive.title;
  let actionTaken: 'created' | 'copied' | 'replaced' = 'created';

  if (wasCollision) {
    if (mode === 'error-if-exists') {
      throw new Error(`COLLISION:${manifest.archive.id}:${manifest.archive.title}`);
    } else if (mode === 'copy') {
      // Create as copy with new ID
      targetArchiveId = `archive_copy_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
      targetTitle = `${manifest.archive.title} (Restored Copy)`;
      actionTaken = 'copied';
    } else if (mode === 'replace') {
      // Replace existing
      await deleteArchive(targetArchiveId);
      actionTaken = 'replaced';
    }
  }

  // 4. Extract attachments
  onProgress?.('Extracting media attachments...');
  const mediaFiles: ImportedMediaFile[] = [];
  const attachmentsFolder = loadedZip.folder('attachments');

  if (attachmentsFolder) {
    const attachmentEntries = Object.values(attachmentsFolder.files).filter((f) => !f.dir);
    for (const entry of attachmentEntries) {
      const fileName = entry.name.split('/').pop() || entry.name;
      const arrayBuf = await entry.async('arraybuffer');
      const blob = new Blob([arrayBuf]);
      mediaFiles.push({
        fileName,
        path: entry.name,
        size: arrayBuf.byteLength,
        type: 'other',
        blob,
      });
    }
  }

  // 5. Restore into IndexedDB
  onProgress?.('Restoring archive to local storage...');
  const db = await getDb();

  // Save attachments
  let totalMediaBytes = 0;
  if (mediaFiles.length > 0) {
    totalMediaBytes = await saveArchiveAttachments(targetArchiveId, mediaFiles);
  }

  // Save messages
  await new Promise<void>((resolve, reject) => {
    const transaction = db.transaction([STORES.MESSAGES], 'readwrite');
    const store = transaction.objectStore(STORES.MESSAGES);

    transaction.onerror = () => reject(transaction.error || new Error('Failed to restore messages'));
    transaction.oncomplete = () => resolve();

    for (const msg of messages) {
      store.put({
        ...msg,
        chatId: targetArchiveId,
      });
    }
  });

  // Save archive metadata
  const restoredArchive: ChatArchiveMetadata = {
    ...manifest.archive,
    id: targetArchiveId,
    title: targetTitle,
    updatedAt: new Date().toISOString(),
    lastOpenedAt: new Date().toISOString(),
    totalMediaSizeBytes: totalMediaBytes || manifest.archive.totalMediaSizeBytes || 0,
    source: {
      type: 'backup-restore',
      originalFileName: manifest.archive.source?.originalFileName || `${targetTitle}.zip`,
      chatFileName: manifest.archive.source?.chatFileName || targetTitle,
    },
  };

  await new Promise<void>((resolve, reject) => {
    const transaction = db.transaction([STORES.ARCHIVES], 'readwrite');
    const store = transaction.objectStore(STORES.ARCHIVES);
    const request = store.put(restoredArchive);

    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error || new Error('Failed to restore archive metadata'));
  });

  return {
    restoredArchive,
    wasCollision,
    actionTaken,
  };
}
